name: "QuickSleep"
main: "navy.warspite.spigot.QuickSleep.Main"
version: "1.0"
api-version: "1.15"
commands:
  getinsomnia:
    description: Get TIME_SINCE_REST
  setinsomnia:
    description: Set TIME_SINCE_REST